name: build ueversionator

on: [ push, pull_request ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: build ueversionator on Windows
      shell: bash
      run: ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: ueversionator.windows
        path: ueversionator.exe

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build ueversionator on Linux
      shell: bash
      run: ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: ueversionator.linux
        path: ueversionator
